services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdataDataMiningProject:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdataDataMiningProject:
