departments: dict[int, str] = {
    1: "Aerospace Engineering",
    2: "Biological Sciences and Bioengineering",
    3: "Civil Engineering",
    4: "Chemical Engineering",
    5: "Chemistry",
    6: "Cognitive Science",
    7: "Computer Science and Engineering",
    8: "Design",
    9: "Economics",
    10: "Electrical Engineering",
    11: "Environmental Engineering and Management",
    12: "Earth Science",
    13: "Humanities and Social Sciences",
    14: "Industrial and Management Engineering",
    15: "Laser Technology",
    16: "Mathematics",
    17: "Mechanical Engineering",
    18: "Materials Science and Engineering",
    19: "Mathematics and Statistics",
    20: "Mathematics and Scientific Computing",
    21: "Materials Science Programme",
    22: "Nuclear Engineering and Technology Programme",
    23: "Physics",
    24: "Photonics Science and Engineering",
    25: "Statistics and Data Science",
    26: "Sustainable Energy Engineering",
    27: "Space Science and Astronomy",
    28: "Statistics",
    29: "Others",
}

branches: dict[int, str] = {
    1: "B.S.",
    2: "B.S.-M.S.",
    3: "B.S.-M.B.A.",
    4: "B.S.-M.Tech",
    5: "B.Tech.-M.S.",
    6: "B.Tech.-M.B.A.",
    7: "B.Tech.-M.Des.",
    8: "B.Tech",
    9: "DIIT",
    10: "Exchange Program",
    11: "M.B.A.",
    12: "M.Sc. (2 yr)",
    13: "M.Sc. (Integrated)",
    14: "M.Sc.-Ph.D. (Dual)",
    15: "M.S. (Research)",
    16: "M.Des.",
    17: "M.Tech",
    18: "M.Tech.-Ph.D.",
    19: "M.Tech. (Dual)",
    20: "PGPEX-VLM",
    21: "Ph.D",
    22: "Preparatory",
    23: "SURGE",
    24: "eMasters",
    25: "Others",
}
