services:
  frontend:
    image: shivinagarwal/dataminingfe
    restart: always
    container_name: frontend
    ports:
      - 80:80
  backend:
    build:
      dockerfile: Dockerfile_local_M3
    restart: always
    container_name: backend
    environment:
      PG_DB_NAME: 'deepfake_db'
      PG_DB_PASSWORD: 'postgres'
      PG_DB_USER: 'postgres'
      PG_DB_HOST: 'db'
      PG_DB_PORT: '5432'
    volumes:
      - ./:/deepfake/
    ports:
      - 8000:8000
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdataDataMiningProject:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdataDataMiningProject:
