services:
  server:
    platform: linux/amd64
    image: nginx:1.25.5-alpine
    container_name: server
    volumes:
      - ./dist:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8123:80"